### ISSUE TITLE
Getting error stating that request module is not installed.

### ISSUE THREAD

**Issue by ryanhaney** [ionic-team/stencil-app-starter#58]
Creating this issue to partially resolve #56, specifically:

```
[ ERROR ]  Cannot find module 'request' at Function.Module._resolveFilename
           (module.js:547:15) at Function.Module._load (module.js:474:25) at
           Module.require (module.js:596:17) at require
           (internal/module.js:11:18) at
           C:\ae\my-app\node_modules\request-promise-native\lib\rp.js:8:12 at
           module.exports
           (C:\ae\my-app\node_modules\stealthy-require\lib\index.js:62:23) at
           Object.<anonymous>
           (C:\ae\my-app\node_modules\request-promise-native\lib\rp.js:7:15) at
           Module._compile (module.js:652:30) at Object.Module._extensions..js
           (module.js:663:10) at Module.load (module.js:565:32)
```

**Comment by Bandito11** [comment]
Ditto for this. And installing request doesn't help. Had to go back to 0.10.10

**Comment by kekscom** [comment]
Installing `request` manually worked for me.

**Comment by ezraroda** [comment]
Same issue, adding request manually didn't work :( 

```
user@MacBookPro WebDev $ npm -v
6.4.1
user@MacBookPro WebDev $ node -v
v8.11.1
user@MacBookPro WebDev $ npm init stencil

✔ Pick a starter › app
✔ Project name › demo-app

✔ All setup  in 1 ms

  Next steps:
   $ cd demo-app
   $ npm start

  Further reading:
   - https://github.com/ionic-team/stencil-app-starter

user@MacBookPro WebDev $ cd demo-app/
user@MacBookPro demo-app $ npm start

> @stencil/starter@0.0.1 start /Users/user/WebDev/demo-app
> stencil build --dev --watch --serve

[11:01.3]  @stencil/core v0.11.0 🍇
[11:01.4]  build, app, dev mode, started ...
[11:01.4]  transpile started ...
[11:02.7]  transpile finished in 1.28 s
[11:02.8]  module map started ...
[11:02.8]  generate styles started ...
[11:03.0]  compile global style start ...
[11:03.1]  compile global style finish in 98 ms
[11:03.1]  generate styles finished in 324 ms
[11:03.3]  module map finished in 504 ms
[11:03.3]  generate bundles started ...
[11:03.3]  generate bundles finished in 3 ms
[11:03.3]  generate app files started ...
[11:04.4]  generate app files finished in 1.11 s

[ ERROR ]  Cannot find module 'request' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load
           (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at
           /Users/user/WebDev/demo-app/node_modules/request-promise-native/lib/rp.js:8:12 at module.exports
           (/Users/user/WebDev/demo-app/node_modules/stealthy-require/lib/index.js:62:23) at
           Object.<anonymous>
           (/Users/user/WebDev/demo-app/node_modules/request-promise-native/lib/rp.js:7:15) at
           Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load
           (module.js:565:32)

[11:04.4]  dev server: http://localhost:3333/
```

Adding request manually didn't work:

```
"devDependencies": {
    "@types/jest": "^23.3.1",
    "jest": "^23.4.2",
    **"request": "^2.87.0"**
  },
```

```
> stencil build --dev --watch --serve

[30:55.3]  @stencil/core v0.11.4 ⛰
[30:55.3]  build, app, dev mode, started ...
[30:55.4]  transpile started ...
[30:55.4]  transpile finished in 16 ms
[30:55.4]  module map started ...
[30:55.4]  generate styles started ...
[30:55.6]  compile global style start ...
[30:55.9]  compile global style finish in 320 ms
[30:55.9]  generate styles finished in 458 ms
[30:56.4]  module map finished in 920 ms

[ ERROR ]  Plugin Error
           Unexpected token (5:22896) in
           /Users/user/WebDev/demo-app/node_modules/@stencil/state-tunnel/dist/esm/es5/stencil-state-tunnel.core.js

[30:56.4]  dev server: http://localhost:3333/
```

**Comment by ezraroda** [comment]
Updating to latest stable "@stencil/core": "0.12.4", worked for me .

```
"dependencies": {
    "@stencil/core": "0.12.4",
    "@stencil/router": "^0.2.5"
  },

```

**Comment by ezraroda** [comment]
Verified , no issues 👍 
Thanks @kensodemann  !
